version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ngs-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - webnet
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngs-ngrok
    restart: unless-stopped
    command:  
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml
    depends_on:
      - nginx
    networks:
      - webnet
networks:
  webnet:
    driver: bridge